import { IconType } from "react-icons";
import {
  FiArrowUpRight,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiChevronUp,
  FiCopy,
  FiDownload,
  FiEdit,
  FiEye,
  FiEyeOff,
  FiLock,
  FiMenu,
  FiMoreHorizontal,
  FiPlus,
  FiSearch,
  FiSettings,
  FiTrash,
  FiUpload,
  FiX,
} from "react-icons/fi";

export const iconLibrary: { [key: string]: IconType } = {
  arrowUpRight: FiArrowUpRight,
  chevronDown: FiChevronDown,
  chevronLeft: FiChevronLeft,
  chevronRight: FiChevronRight,
  chevronUp: FiChevronUp,
  copy: FiCopy,
  download: FiDownload,
  edit: FiEdit,
  eye: FiEye,
  eyeOff: FiEyeOff,
  lock: FiLock,
  menu: FiMenu,
  moreHorizontal: FiMoreHorizontal,
  plus: FiPlus,
  search: FiSearch,
  settings: FiSettings,
  trash: FiTrash,
  upload: FiUpload,
  x: FiX,
};
